# Generated by Plain 0.165.0 on 2026-10-03 22:38

import plain.passwords.models
import plain.passwords.validators
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("email", postgres.EmailField()),
                ("is_admin", postgres.BooleanField(default=False)),
                (
                    "password",
                    plain.passwords.models.PasswordField(
                        validators=[
                            plain.passwords.validators.MinimumLengthValidator(),
                            plain.passwords.validators.CommonPasswordValidator(),
                            plain.passwords.validators.NumericPasswordValidator(),
                        ]
                    ),
                ),
                (
                    "time_zone",
                    postgres.TimeZoneField(allow_null=True, default=None, required=False),
                ),
            ],
        ),
    )
