# Generated by Plain 0.165.0 on 2026-10-03 22:45

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("config", postgres.JSONField(default={})),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("description", postgres.TextField(default="", required=False)),
                ("name", postgres.TextField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("key", postgres.TextField()),
                ("value", postgres.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("domain", postgres.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("config", postgres.JSONField(default={})),
                ("enabled", postgres.BooleanField(default=True)),
                (
                    "kind",
                    postgres.TextField(
                        choices=[("local", "Local Chrome"), ("browserbase", "Browserbase")]
                    ),
                ),
                ("name", postgres.TextField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("username", postgres.TextField(default="", required=False)),
                (
                    "persona",
                    postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.persona"),
                ),
                ("site", postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.site")),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("actor", postgres.TextField()),
                ("checked_in_at", postgres.DateTimeField(allow_null=True)),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("finished_at", postgres.DateTimeField(allow_null=True)),
                ("issues", postgres.JSONField(default=[])),
                ("plan", postgres.JSONField(default=[])),
                ("promoted", postgres.BooleanField(default=False)),
                (
                    "promotion_reason",
                    postgres.TextField(default="Awaiting check-in", required=False),
                ),
                ("runtime", postgres.JSONField(default={})),
                ("scope", postgres.TextField(default="*", max_length=255)),
                ("started_at", postgres.DateTimeField(allow_null=True)),
                (
                    "status",
                    postgres.TextField(
                        choices=[
                            ("queued", "queued"),
                            ("starting", "starting"),
                            ("running", "running"),
                            ("finishing", "finishing"),
                            ("success", "success"),
                            ("failed", "failed"),
                            ("abandoned", "abandoned"),
                        ],
                        default="queued",
                    ),
                ),
                ("tip", postgres.TextField(default="", required=False)),
                (
                    "persona",
                    postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.persona"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("check_id", postgres.IntegerField()),
                ("classification", postgres.JSONField(default={})),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("evidence", postgres.JSONField(default={})),
                ("passed", postgres.BooleanField(default=False)),
                ("state", postgres.TextField()),
                ("run", postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.run")),
            ],
        ),
        migrations.CreateModel(
            name="Checkpoint",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("actor", postgres.TextField()),
                ("branch", postgres.TextField(default="", required=False)),
                ("coverage", postgres.JSONField(default={})),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("digest", postgres.TextField(max_length=64)),
                ("message", postgres.TextField()),
                ("parent", postgres.TextField(default="", required=False)),
                ("source", postgres.JSONField(default={})),
                ("summary", postgres.JSONField(default={})),
                (
                    "persona",
                    postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.persona"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="run",
            name="base",
            field=postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.checkpoint"),
        ),
        migrations.CreateModel(
            name="Leader",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("finished_at", postgres.DateTimeField(allow_null=True)),
                ("scope", postgres.TextField(default="*", max_length=255)),
                ("verified", postgres.BooleanField(default=False)),
                (
                    "persona",
                    postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.persona"),
                ),
                (
                    "checkpoint",
                    postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.checkpoint"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="run",
            name="provider",
            field=postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.provider"),
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("assertions", postgres.JSONField(default={})),
                ("enabled", postgres.BooleanField(default=True)),
                ("instruction", postgres.TextField(default="", required=False)),
                ("interval_seconds", postgres.IntegerField(default=3600)),
                ("name", postgres.TextField(max_length=160)),
                ("next_due", postgres.DateTimeField(allow_null=True)),
                ("url", postgres.URLField()),
                (
                    "account",
                    postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.account"),
                ),
                (
                    "provider",
                    postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.provider"),
                ),
            ],
        ),
    )
