# Generated by Plain 0.165.0 on 2026-10-03 23:33

from plain.postgres import migrations


class Migration(migrations.Migration):
    dependencies = (("core", "0001_initial"),)

    operations = (
        migrations.RemoveField(
            model_name="check",
            name="assertions",
        ),
    )
