# Generated by Plain 0.165.0 on 2026-10-04 02:10

from plain import postgres
from plain.postgres import migrations

import app.core.providers


class Migration(migrations.Migration):
    dependencies = (("core", "0002_remove_check_assertions"),)

    operations = (
        migrations.AlterField(
            model_name="provider",
            name="kind",
            field=postgres.TextField(
                max_length=64, validators=[app.core.providers.validate_provider_kind]
            ),
        ),
    )
