# Generated by Plain 0.165.0 on 2026-10-04 02:32

from plain import postgres
from plain.postgres import migrations

import app.core.models
import app.core.services


class Migration(migrations.Migration):
    atomic = False

    dependencies = (("core", "0003_provider_adapter_registry"),)

    operations = (
        migrations.CreateModel(
            name="CheckEvent",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("actor", postgres.TextField()),
                ("check_run_uid", postgres.UUIDField(allow_null=True, required=False)),
                ("check_uid", postgres.UUIDField()),
                ("kind", postgres.TextField(max_length=64)),
                ("occurred_at", postgres.DateTimeField(create_now=True)),
                ("payload", postgres.JSONField(default={}, required=False)),
                ("uid", app.core.models.UUID7Field()),
            ],
        ),
        migrations.AddField(
            model_name="check",
            name="uid",
            field=app.core.models.UUID7Field(),
        ),
        migrations.CreateModel(
            name="CheckType",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("author", postgres.TextField()),
                ("check_id", postgres.IntegerField()),
                ("code", postgres.TextField()),
                ("created_at", postgres.DateTimeField(create_now=True)),
                ("digest", postgres.TextField(max_length=64)),
                ("lang", postgres.TextField(max_length=32)),
                ("name", postgres.TextField()),
                ("uid", app.core.models.UUID7Field()),
                (
                    "previous",
                    postgres.ForeignKeyField(
                        allow_null=True,
                        on_delete=postgres.RESTRICT,
                        required=False,
                        to="core.checktype",
                    ),
                ),
            ],
        ),
        migrations.AlterModelTable(
            name="observation",
            table="core_observation",
        ),
        migrations.RenameModel(
            old_name="Observation",
            new_name="CheckRun",
        ),
        migrations.AddField(
            model_name="checkrun",
            name="artifact_dir",
            field=postgres.TextField(default="", required=False),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="ended_at",
            field=postgres.DateTimeField(allow_null=True, required=False),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="error",
            field=postgres.TextField(default="", required=False),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="raw_output",
            field=postgres.TextField(default="", required=False),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="screenshot",
            field=postgres.TextField(default="", required=False),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="started_at",
            field=postgres.DateTimeField(allow_null=True, required=False),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="status",
            field=postgres.TextField(
                choices=[("running", "running"), ("success", "success"), ("failure", "failure")],
                default="running",
            ),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="summary",
            field=postgres.TextField(default="", required=False),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="uid",
            field=app.core.models.UUID7Field(),
        ),
        migrations.AddField(
            model_name="checkrun",
            name="timing_source",
            field=postgres.TextField(default="", required=False),
        ),
        migrations.AlterField(
            model_name="checkrun",
            name="state",
            field=postgres.TextField(default="", required=False),
        ),
        migrations.CreateModel(
            name="CheckRunStep",
            fields=[
                ("id", postgres.PrimaryKeyField()),
                ("ended_at", postgres.DateTimeField(allow_null=True, required=False)),
                ("inputs", postgres.JSONField(default={}, required=False)),
                ("output_path", postgres.TextField()),
                ("outputs", postgres.JSONField(default={}, required=False)),
                ("position", postgres.IntegerField()),
                ("source_path", postgres.TextField()),
                ("started_at", postgres.DateTimeField(allow_null=True, required=False)),
                ("step", postgres.TextField(max_length=64)),
                ("uid", app.core.models.UUID7Field()),
                (
                    "check_run",
                    postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.checkrun"),
                ),
                (
                    "check_type",
                    postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to="core.checktype"),
                ),
                (
                    "timing_source",
                    postgres.TextField(default="artifact file timestamps", required=False),
                ),
            ],
        ),
        migrations.RunPython(
            code=app.core.services.backfill_check_history,
            atomic=False,
        ),
        migrations.RunSQL(
            sql="CREATE FUNCTION account_checker_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Check history is append-only'; END $$;\nCREATE TRIGGER check_event_append_only BEFORE UPDATE OR DELETE ON core_checkevent FOR EACH ROW EXECUTE FUNCTION account_checker_append_only();\nCREATE TRIGGER check_type_append_only BEFORE UPDATE OR DELETE ON core_checktype FOR EACH ROW EXECUTE FUNCTION account_checker_append_only();\nCREATE TRIGGER check_step_append_only BEFORE UPDATE OR DELETE ON core_checkrunstep FOR EACH ROW EXECUTE FUNCTION account_checker_append_only();",
        ),
    )
