# Generated by Plain 0.165.0 on 2026-10-04 02:36

from plain.postgres import migrations

from app.core.services import backfill_check_history


class Migration(migrations.Migration):
    atomic = False

    dependencies = (("core", "0004_check_execution_history"),)

    operations = (migrations.RunPython(backfill_check_history, atomic=False),)
