# Generated by Plain 0.165.0 on 2026-10-04 08:19

from plain import postgres
from plain.postgres import migrations

import app.core.domain_patterns


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0005_recover_interrupted_check_programs'),
    )

    operations = (
        migrations.AddField(
            model_name='checktype',
            name='domain',
            field=postgres.TextField(default='*', validators=[app.core.domain_patterns.validate]),
        ),
    )
