# Generated by Plain 0.165.0 on 2026-10-04 09:26

import app.core.domain_patterns
import app.core.models
from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0008_persona_leader'),
    )

    operations = (
        migrations.CreateModel(
            name='FixType',
            fields=[
                ('id', postgres.PrimaryKeyField()),
                ('author', postgres.TextField()),
                ('created_at', postgres.DateTimeField(create_now=True)),
                ('domain', postgres.TextField(default='*', validators=[app.core.domain_patterns.validate])),
                ('enabled', postgres.BooleanField(default=True)),
                ('key', postgres.TextField()),
                ('name', postgres.TextField(max_length=160)),
                ('prompt', postgres.TextField()),
                ('uid', app.core.models.UUID7Field()),
                ('previous', postgres.ForeignKeyField(allow_null=True, on_delete=postgres.RESTRICT, required=False, to='core.fixtype')),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='fix_type',
            field=postgres.ForeignKeyField(allow_null=True, on_delete=postgres.RESTRICT, required=False, to='core.fixtype'),
        ),
    )
