# Generated by Plain 0.165.0 on 2026-10-04 09:30

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0010_default_login_fix'),
    )

    operations = (
        migrations.RemoveField(
            model_name='run',
            name='fix_type',
        ),
        migrations.AddField(
            model_name='check',
            name='mode',
            field=postgres.TextField(choices=[('check', 'Check'), ('fix', 'Fix')], default='check'),
        ),
        migrations.DeleteModel(
            name='FixType',
        ),
    )
