# Generated by Plain 0.165.0 on 2026-10-04 09:31

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0011_remove_run_fix_type_check_mode_delete_fixtype'),
    )

    operations = (
        migrations.AddField(
            model_name='check',
            name='pattern',
            field=postgres.TextField(default='', required=False),
        ),
        migrations.AddField(
            model_name='check',
            name='source_task',
            field=postgres.ForeignKeyField(allow_null=True, on_delete=postgres.RESTRICT, required=False, to='core.check'),
        ),
        migrations.AddField(
            model_name='run',
            name='triggered_by',
            field=postgres.ForeignKeyField(allow_null=True, on_delete=postgres.RESTRICT, required=False, to='core.run'),
        ),
        migrations.CreateModel(
            name='TaskRule',
            fields=[
                ('id', postgres.PrimaryKeyField()),
                ('created_at', postgres.DateTimeField(create_now=True)),
                ('enabled', postgres.BooleanField(default=True)),
                ('state', postgres.TextField(default='', required=False)),
                ('status', postgres.TextField(choices=[('failure', 'Failed'), ('success', 'Passed')], default='failure')),
                ('source', postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to='core.check')),
                ('target', postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to='core.check')),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='rule',
            field=postgres.ForeignKeyField(allow_null=True, on_delete=postgres.RESTRICT, required=False, to='core.taskrule'),
        ),
    )
