# Generated by Plain 0.165.0 on 2026-10-04 09:51

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0012_check_pattern_check_source_task_run_triggered_by_and_more'),
    )

    operations = (
        migrations.CreateModel(
            name='LeaderChange',
            fields=[
                ('id', postgres.PrimaryKeyField()),
                ('actor', postgres.TextField()),
                ('created_at', postgres.DateTimeField(create_now=True)),
                ('kind', postgres.TextField(choices=[('initial', 'initial'), ('import', 'import'), ('adopt', 'adopt'), ('restore', 'restore')])),
                ('checkpoint', postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to='core.checkpoint')),
                ('persona', postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to='core.persona')),
                ('previous', postgres.ForeignKeyField(allow_null=True, on_delete=postgres.RESTRICT, required=False, to='core.checkpoint')),
                ('run', postgres.ForeignKeyField(allow_null=True, on_delete=postgres.RESTRICT, required=False, to='core.run')),
            ],
        ),
    )
