# Generated by Plain 0.165.0 on 2026-10-04 10:06

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0013_leaderchange'),
    )

    operations = (
        migrations.AddField(
            model_name='provider',
            name='color',
            field=postgres.TextField(default='', max_length=7, required=False),
        ),
    )
