# Generated by Plain 0.165.0 on 2026-10-04 10:45

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0014_provider_color'),
    )

    operations = (
        migrations.AddField(
            model_name='provider',
            name='site_scope',
            field=postgres.JSONField(allow_null=True, default=None, required=False),
        ),
    )
