# Generated by Plain 0.165.0 on 2026-10-05 23:56

from plain import postgres
from plain.postgres import migrations

import app.core.models


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0015_provider_site_scope'),
    )

    operations = (
        migrations.AddField(
            model_name='persona',
            name='uid',
            field=app.core.models.UUID7Field(),
        ),
        migrations.AddField(
            model_name='provider',
            name='uid',
            field=app.core.models.UUID7Field(),
        ),
        migrations.CreateModel(
            name='PersonaProviderConfig',
            fields=[
                ('id', postgres.PrimaryKeyField()),
                ('config', postgres.JSONField(default={}, required=False)),
                ('persona', postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to='core.persona')),
                ('provider', postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to='core.provider')),
            ],
        ),
        migrations.CreateModel(
            name='IPUsage',
            fields=[
                ('id', postgres.PrimaryKeyField()),
                ('ended_at', postgres.DateTimeField()),
                ('geo', postgres.JSONField(default={}, required=False)),
                ('ip', postgres.TextField(max_length=45)),
                ('scope', postgres.TextField(default='probe')),
                ('source', postgres.TextField(default='browser')),
                ('started_at', postgres.DateTimeField()),
                ('run', postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to='core.run')),
            ],
        ),
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', postgres.PrimaryKeyField()),
                ('created_at', postgres.DateTimeField(create_now=True)),
                ('deadline', postgres.DateTimeField(allow_null=True, required=False)),
                ('detail', postgres.JSONField(default={}, required=False)),
                ('expires_at', postgres.DateTimeField(allow_null=True, required=False)),
                ('key', postgres.TextField(allow_null=True, default=None, required=False)),
                ('spec', postgres.JSONField()),
                ('status', postgres.TextField(default='queued')),
                ('uid', app.core.models.UUID7Field()),
                ('run', postgres.ForeignKeyField(allow_null=True, on_delete=postgres.RESTRICT, required=False, to='core.run')),
            ],
        ),
    )
