# Generated by Plain 0.165.0 on 2026-10-06 01:36

from plain.postgres import migrations


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0016_persona_uid_provider_uid_personaproviderconfig_and_more'),
    )

    operations = (
        migrations.RemoveField(
            model_name='ipusage',
            name='scope',
        ),
    )
