# Generated by Plain 0.165.0 on 2026-10-08 06:22

from plain import postgres
from plain.postgres import migrations


class Migration(migrations.Migration):

    dependencies = (
        ('core', '0017_remove_ipusage_scope'),
    )

    operations = (
        migrations.CreateModel(
            name='PersonaSetup',
            fields=[
                ('id', postgres.PrimaryKeyField()),
                ('completed', postgres.JSONField(default=[], required=False)),
                ('created_at', postgres.DateTimeField(create_now=True)),
                ('key', postgres.UUIDField()),
                ('private_data', postgres.TextField()),
                ('status', postgres.TextField(default='draft')),
                ('persona', postgres.ForeignKeyField(on_delete=postgres.RESTRICT, to='core.persona')),
                ('run', postgres.ForeignKeyField(allow_null=True, on_delete=postgres.RESTRICT, required=False, to='core.run')),
            ],
        ),
    )
