from datetime import datetime
from uuid import UUID

from plain import postgres
from plain.postgres import Field, types
from plain.postgres.expressions import Func

from .domain_patterns import validate as validate_domains
from .providers import validate_provider_kind


class UUID7Field(types.UUIDField):
    """Public identifiers generated by the workspace's PostgreSQL 18 server."""

    def get_db_default_expression(self):
        return Func(function="uuidv7", output_field=types.UUIDField())


@postgres.register_model
class Persona(postgres.Model):
    name: Field[str] = types.TextField(max_length=160)
    description: Field[str] = types.TextField(default="", required=False)
    config: Field[dict] = types.JSONField(default={}, required=False)
    created_at: Field[datetime] = types.DateTimeField(create_now=True)


@postgres.register_model
class Site(postgres.Model):
    domain: Field[str] = types.TextField(max_length=255)
    model_options = postgres.Options(
        constraints=[postgres.UniqueConstraint(fields=["domain"], name="site_domain")]
    )


@postgres.register_model
class Account(postgres.Model):
    persona: Field[Persona] = types.ForeignKeyField(Persona, on_delete=postgres.RESTRICT)
    site: Field[Site] = types.ForeignKeyField(Site, on_delete=postgres.RESTRICT)
    username: Field[str] = types.TextField(default="", required=False)
    model_options = postgres.Options(
        constraints=[postgres.UniqueConstraint(fields=["persona", "site"], name="persona_site")],
        indexes=[postgres.Index(fields=["site"], name="account_site_idx")],
    )


    def __str__(self):
        return f"{self.persona.name} · {self.site.domain} · {self.username}"


@postgres.register_model
class Provider(postgres.Model):
    site_scope: Field[list | None] = types.JSONField(default=None, allow_null=True, required=False)
    color: Field[str] = types.TextField(default='', required=False, max_length=7)
    name: Field[str] = types.TextField(max_length=160)
    kind: Field[str] = types.TextField(max_length=64, validators=[validate_provider_kind])
    config: Field[dict] = types.JSONField(default={}, required=False)
    enabled: Field[bool] = types.BooleanField(default=True)


    def __str__(self):
        return self.name

    @property
    def display_color(self):
        return self.color or ('#4f73c4', '#a56bcd', '#cd7b36', '#339c99')[self.id % 4]


@postgres.register_model
class Check(postgres.Model):
    mode: Field[str] = types.TextField(default="check", choices=[("check", "Check"), ("fix", "Fix")])
    source_task: Field[Check | None] = types.ForeignKeyField('self', on_delete=postgres.RESTRICT,
        allow_null=True, default=None, required=False)
    pattern: Field[str] = types.TextField(default='', required=False)
    uid: Field[UUID] = UUID7Field()
    account: Field[Account] = types.ForeignKeyField(Account, on_delete=postgres.RESTRICT)
    provider: Field[Provider] = types.ForeignKeyField(Provider, on_delete=postgres.RESTRICT)
    name: Field[str] = types.TextField(max_length=160)
    instruction: Field[str] = types.TextField()
    url: Field[str] = types.URLField()
    interval_seconds: Field[int] = types.IntegerField(default=3600)
    enabled: Field[bool] = types.BooleanField(default=True)
    next_due: Field[datetime | None] = types.DateTimeField(
        allow_null=True, default=None, required=False
    )
    model_options = postgres.Options(
        constraints=[postgres.UniqueConstraint(fields=["uid"], name="check_uid")],
        indexes=[
            postgres.Index(fields=["account"], name="check_account_idx"),
            postgres.Index(fields=["provider"], name="check_provider_idx"),
            postgres.Index(fields=['source_task'], name='task_source_idx'),
        ],
    )

    def __str__(self):
        return f'{self.account.persona.name} · {self.account.site.domain} · {self.provider.name} · {self.name}'


@postgres.register_model
class TaskRule(postgres.Model):
    source: Field[Check] = types.ForeignKeyField(Check, on_delete=postgres.RESTRICT)
    target: Field[Check] = types.ForeignKeyField(Check, on_delete=postgres.RESTRICT)
    status: Field[str] = types.TextField(default='failure', choices=[('failure', 'Failed'), ('success', 'Passed')])
    state: Field[str] = types.TextField(default='', required=False)
    enabled: Field[bool] = types.BooleanField(default=True)
    created_at: Field[datetime] = types.DateTimeField(create_now=True)
    model_options = postgres.Options(
        constraints=[postgres.UniqueConstraint(fields=['source', 'target', 'status', 'state'], name='task_rule_edge')],
        indexes=[postgres.Index(fields=['target'], name='rule_target_idx')],
    )


@postgres.register_model
class Checkpoint(postgres.Model):
    persona: Field[Persona] = types.ForeignKeyField(Persona, on_delete=postgres.RESTRICT)
    digest: Field[str] = types.TextField(max_length=64)
    parent: Field[str] = types.TextField(default="", required=False)
    branch: Field[str] = types.TextField(default="", required=False)
    message: Field[str] = types.TextField()
    actor: Field[str] = types.TextField()
    source: Field[dict] = types.JSONField(default={}, required=False)
    summary: Field[dict] = types.JSONField(default={}, required=False)
    coverage: Field[dict] = types.JSONField(default={}, required=False)
    created_at: Field[datetime] = types.DateTimeField(create_now=True)
    model_options = postgres.Options(
        constraints=[postgres.UniqueConstraint(fields=["digest"], name="checkpoint_digest")],
        indexes=[
            postgres.Index(
                fields=["persona", "created_at"], name="checkpoint_persona_created_at_idx"
            )
        ],
    )


@postgres.register_model
class Leader(postgres.Model):
    persona: Field[Persona] = types.ForeignKeyField(Persona, on_delete=postgres.RESTRICT)
    checkpoint: Field[Checkpoint] = types.ForeignKeyField(Checkpoint, on_delete=postgres.RESTRICT)
    verified: Field[bool] = types.BooleanField(default=False)
    finished_at: Field[datetime | None] = types.DateTimeField(
        allow_null=True, default=None, required=False
    )
    model_options = postgres.Options(
        constraints=[postgres.UniqueConstraint(fields=["persona"], name="persona_leader")],
        indexes=[postgres.Index(fields=["checkpoint"], name="leader_checkpoint_idx")],
    )


@postgres.register_model
class Run(postgres.Model):
    triggered_by: Field[Run | None] = types.ForeignKeyField('self', on_delete=postgres.RESTRICT,
        allow_null=True, default=None, required=False)
    rule: Field[TaskRule | None] = types.ForeignKeyField(TaskRule, on_delete=postgres.RESTRICT,
        allow_null=True, default=None, required=False)
    persona: Field[Persona] = types.ForeignKeyField(Persona, on_delete=postgres.RESTRICT)
    provider: Field[Provider] = types.ForeignKeyField(Provider, on_delete=postgres.RESTRICT)
    base: Field[Checkpoint] = types.ForeignKeyField(Checkpoint, on_delete=postgres.RESTRICT)
    tip: Field[str] = types.TextField(default="", required=False)
    scope: Field[str] = types.TextField(default="*", max_length=255)
    status: Field[str] = types.TextField(
        default="queued",
        choices=[
            (s, s)
            for s in [
                "queued",
                "starting",
                "running",
                "finishing",
                "success",
                "failed",
                "abandoned",
            ]
        ],
    )
    issues: Field[list] = types.JSONField(default=[], required=False)
    plan: Field[list] = types.JSONField(default=[], required=False)
    runtime: Field[dict] = types.JSONField(default={}, required=False)
    actor: Field[str] = types.TextField()
    created_at: Field[datetime] = types.DateTimeField(create_now=True)
    started_at: Field[datetime | None] = types.DateTimeField(
        allow_null=True, default=None, required=False
    )
    finished_at: Field[datetime | None] = types.DateTimeField(
        allow_null=True, default=None, required=False
    )
    checked_in_at: Field[datetime | None] = types.DateTimeField(
        allow_null=True, default=None, required=False
    )
    promoted: Field[bool] = types.BooleanField(default=False)
    promotion_reason: Field[str] = types.TextField(default="Awaiting check-in", required=False)
    model_options = postgres.Options(
        constraints=[postgres.UniqueConstraint(fields=['triggered_by', 'rule'], name='task_rule_dispatch')],
        indexes=[
            postgres.Index(fields=['rule'], name='run_rule_idx'),
            postgres.Index(fields=["persona", "created_at"], name="run_persona_created_at_idx"),
            postgres.Index(fields=["provider"], name="run_provider_idx"),
            postgres.Index(fields=["base"], name="run_base_idx"),
            postgres.Index(fields=["status", "created_at"], name="run_status_created_at_idx"),
        ]
    )


@postgres.register_model
class CheckType(postgres.Model):
    """An immutable hand-authored or agent-authored script revision."""

    uid: Field[UUID] = UUID7Field()
    check_id: Field[int | None] = types.IntegerField(allow_null=True, default=None, required=False)
    previous: Field[CheckType | None] = types.ForeignKeyField(
        "self", on_delete=postgres.RESTRICT, allow_null=True, default=None, required=False
    )
    name: Field[str] = types.TextField()
    domain: Field[str] = types.TextField(default="*", validators=[validate_domains])
    lang: Field[str] = types.TextField(max_length=32)
    code: Field[str] = types.TextField()
    digest: Field[str] = types.TextField(max_length=64)
    author: Field[str] = types.TextField()
    created_at: Field[datetime] = types.DateTimeField(create_now=True)
    model_options = postgres.Options(
        constraints=[
            postgres.UniqueConstraint(fields=["uid"], name="check_type_uid"),
        ],
        indexes=[
            postgres.Index(fields=["previous"], name="check_type_previous_idx"),
            postgres.Index(fields=["check_id", "created_at"], name="check_type_history_idx"),
        ],
    )


@postgres.register_model
class CheckRun(postgres.Model):
    uid: Field[UUID] = UUID7Field()
    run: Field[Run] = types.ForeignKeyField(Run, on_delete=postgres.RESTRICT)
    check_id: Field[int] = types.IntegerField()
    started_at: Field[datetime | None] = types.DateTimeField(
        allow_null=True, default=None, required=False
    )
    ended_at: Field[datetime | None] = types.DateTimeField(
        allow_null=True, default=None, required=False
    )
    timing_source: Field[str] = types.TextField(default="", required=False)
    status: Field[str] = types.TextField(
        default="running", choices=[(s, s) for s in ("running", "success", "failure")]
    )
    artifact_dir: Field[str] = types.TextField(default="", required=False)
    screenshot: Field[str] = types.TextField(default="", required=False)
    raw_output: Field[str] = types.TextField(default="", required=False)
    summary: Field[str] = types.TextField(default="", required=False)
    error: Field[str] = types.TextField(default="", required=False)
    state: Field[str] = types.TextField(default="", required=False)
    passed: Field[bool] = types.BooleanField(default=False)
    evidence: Field[dict] = types.JSONField(default={}, required=False)
    classification: Field[dict] = types.JSONField(default={}, required=False)
    created_at: Field[datetime] = types.DateTimeField(create_now=True)
    model_options = postgres.Options(
        db_table="core_observation",
        constraints=[postgres.UniqueConstraint(fields=["uid"], name="check_run_uid")],
        indexes=[
            postgres.Index(fields=["run", "created_at"], name="observation_run_created_at_idx"),
            postgres.Index(fields=["check_id", "ended_at"], name="check_run_check_ended_idx"),
        ],
    )


@postgres.register_model
class CheckRunStep(postgres.Model):
    uid: Field[UUID] = UUID7Field()
    check_run: Field[CheckRun] = types.ForeignKeyField(CheckRun, on_delete=postgres.RESTRICT)
    check_type: Field[CheckType] = types.ForeignKeyField(CheckType, on_delete=postgres.RESTRICT)
    position: Field[int] = types.IntegerField()
    step: Field[str] = types.TextField(max_length=64)
    started_at: Field[datetime | None] = types.DateTimeField(
        allow_null=True, default=None, required=False
    )
    ended_at: Field[datetime | None] = types.DateTimeField(
        allow_null=True, default=None, required=False
    )
    timing_source: Field[str] = types.TextField(default="artifact file timestamps", required=False)
    inputs: Field[dict] = types.JSONField(default={}, required=False)
    outputs: Field[dict] = types.JSONField(default={}, required=False)
    source_path: Field[str] = types.TextField()
    output_path: Field[str] = types.TextField()
    model_options = postgres.Options(
        constraints=[
            postgres.UniqueConstraint(fields=["uid"], name="check_run_step_uid"),
            postgres.UniqueConstraint(fields=["check_run", "step"], name="check_run_step_identity"),
        ],
        indexes=[postgres.Index(fields=["check_type"], name="check_step_type_idx")],
    )


@postgres.register_model
class CheckEvent(postgres.Model):
    """Append-only facts; existing condition/result rows are current projections."""

    uid: Field[UUID] = UUID7Field()
    occurred_at: Field[datetime] = types.DateTimeField(create_now=True)
    check_uid: Field[UUID] = types.UUIDField()
    check_run_uid: Field[UUID | None] = types.UUIDField(
        allow_null=True, default=None, required=False
    )
    kind: Field[str] = types.TextField(max_length=64)
    actor: Field[str] = types.TextField()
    payload: Field[dict] = types.JSONField(default={}, required=False)
    model_options = postgres.Options(
        constraints=[postgres.UniqueConstraint(fields=["uid"], name="check_event_uid")],
        indexes=[postgres.Index(fields=["check_uid", "occurred_at"], name="check_event_time_idx")],
    )


@postgres.register_model
class AppConfig(postgres.Model):
    key: Field[str] = types.TextField()
    value: Field[dict] = types.JSONField(default={}, required=False)
    model_options = postgres.Options(
        constraints=[postgres.UniqueConstraint(fields=["key"], name="app_config_key")]
    )


@postgres.register_model
class LeaderChange(postgres.Model):
    """Actual updates to the persona's leader pointer, separate from snapshot ancestry."""

    persona: Field[Persona] = types.ForeignKeyField(Persona, on_delete=postgres.RESTRICT)
    checkpoint: Field[Checkpoint] = types.ForeignKeyField(Checkpoint, on_delete=postgres.RESTRICT)
    previous: Field[Checkpoint | None] = types.ForeignKeyField(Checkpoint, on_delete=postgres.RESTRICT, allow_null=True, default=None, required=False)
    run: Field[Run | None] = types.ForeignKeyField(Run, on_delete=postgres.RESTRICT, allow_null=True, default=None, required=False)
    kind: Field[str] = types.TextField(choices=[(k, k) for k in ('initial', 'import', 'adopt', 'restore')])
    actor: Field[str] = types.TextField()
    created_at: Field[datetime] = types.DateTimeField(create_now=True)
    model_options = postgres.Options(indexes=[
        postgres.Index(fields=['persona', 'created_at'], name='leader_change_time_idx'),
        postgres.Index(fields=['checkpoint'], name='leader_change_checkpoint_idx'),
        postgres.Index(fields=['previous'], name='leader_change_previous_idx'),
        postgres.Index(fields=['run'], name='leader_change_run_idx'),
    ])
